[package]
name = "biopix"
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = "0.30.2"
winit = "0.27.5"
raw-window-handle = "0.5.0"
glutin-winit = "0.2.1"
png = { version = "0.17.6", optional = true }
obj-rs = "0.7.0"

[build-dependencies]
gl_generator = "0.14"
cfg_aliases = "0.1.1"
